# Generated by Django 3.2.15 on 2022-11-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesionnaires',
            new_name='questionnaires',
        ),
    ]
