# Generated by Django 3.2.15 on 2022-11-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_rename_quesionnaires_question_questionnaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaires',
            field=models.ManyToManyField(related_name='questions', to='questionnaires.Questionnaire'),
        ),
        migrations.CreateModel(
            name='OptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.option')),
                ('question_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionentry')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question'),
        ),
    ]
