# Generated by Django 3.2.15 on 2022-11-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20221116_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='OptionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_default', models.CharField(default='Enter answer here', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='OptionNumeric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(default=1)),
                ('max_value', models.IntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='optionentry',
            name='option_choice',
        ),
        migrations.RemoveField(
            model_name='optionentry',
            name='question_entry',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionnaires',
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaires.question')),
                ('questionnaires', models.ManyToManyField(related_name='choicequestions', to='questionnaires.Questionnaire')),
            ],
            bases=('questionnaires.question',),
        ),
        migrations.CreateModel(
            name='QuestionInput',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaires.question')),
                ('questionnaires', models.ManyToManyField(related_name='inputquestions', to='questionnaires.Questionnaire')),
            ],
            bases=('questionnaires.question',),
        ),
        migrations.CreateModel(
            name='QuestionNumeric',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaires.question')),
                ('questionnaires', models.ManyToManyField(related_name='numericquestions', to='questionnaires.Questionnaire')),
            ],
            bases=('questionnaires.question',),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionEntry',
        ),
        migrations.AddField(
            model_name='optionnumeric',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionnumerics', to='questionnaires.questionnumeric'),
        ),
        migrations.AddField(
            model_name='optioninput',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optioninputs', to='questionnaires.questioninput'),
        ),
        migrations.AddField(
            model_name='optionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionchoices', to='questionnaires.questionchoice'),
        ),
    ]
