# Generated by Django 3.2.15 on 2022-11-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_auto_20221116_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionchoice',
            old_name='option_text',
            new_name='option_value',
        ),
        migrations.RenameField(
            model_name='optioninput',
            old_name='input_default',
            new_name='standard_text',
        ),
    ]
