# Generated by Django 3.2.15 on 2022-11-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221114_1327'),
        ('questionnaires', '0005_auto_20221116_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionEntry',
            new_name='QuestionInputEntry',
        ),
        migrations.AlterField(
            model_name='questioninputentry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questioninput'),
        ),
        migrations.CreateModel(
            name='QuestionNumericEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.IntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnumeric')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.CharField(max_length=100)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionchoice')),
            ],
        ),
    ]
