# Generated by Django 3.2.15 on 2022-11-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_remove_questioninputentry_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninputentry',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questioninput'),
            preserve_default=False,
        ),
    ]
