# Generated by Django 3.2.15 on 2022-11-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221124_1547'),
        ('questionnaires', '0008_questioninputentry_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoiceentry',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choiceentries', to='users.client'),
        ),
        migrations.AlterField(
            model_name='questionchoiceentry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choiceentries', to='questionnaires.questionchoice'),
        ),
        migrations.AlterField(
            model_name='questioninputentry',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputentries', to='users.client'),
        ),
        migrations.AlterField(
            model_name='questioninputentry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputentries', to='questionnaires.questioninput'),
        ),
        migrations.AlterField(
            model_name='questionnumericentry',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numericentries', to='users.client'),
        ),
        migrations.AlterField(
            model_name='questionnumericentry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numericentries', to='questionnaires.questionnumeric'),
        ),
    ]
