# Generated by Django 3.2.15 on 2022-12-02 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221124_1547'),
        ('questionnaires', '0009_auto_20221124_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoiceentry',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 1, 57, 750666)),
        ),
        migrations.AlterField(
            model_name='questioninputentry',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 1, 57, 749671)),
        ),
        migrations.AlterField(
            model_name='questionnumericentry',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 1, 57, 750666)),
        ),
        migrations.CreateModel(
            name='QuestionnaireEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 1, 57, 742671))),
                ('is_completed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaires.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='questionchoiceentry',
            name='questionnaire_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choiceentries', to='questionnaires.questionnaireentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioninputentry',
            name='questionnaire_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inputentries', to='questionnaires.questionnaireentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnumericentry',
            name='questionnaire_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='numericentries', to='questionnaires.questionnaireentry'),
            preserve_default=False,
        ),
    ]
