# Generated by Django 4.1.3 on 2022-11-29 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Healper', max_length=12)),
                ('text', models.CharField(default='Healper notification', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_type', models.CharField(choices=[('day', 'Daily'), ('hour', 'Hourly'), ('minute', 'Minutely'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('second', 'Secondly'), ('week', 'Weekly'), ('year', 'Yearly')], default='day', max_length=7)),
                ('separation_count', models.IntegerField(default=0)),
                ('max_numb_occurrences', models.IntegerField(null=True)),
                ('day_of_week', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('day_of_month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('week_of_month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('month_of_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval', to='notifications.notification')),
            ],
        ),
    ]
