# Generated by Django 4.1.3 on 2022-11-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_interval_day_of_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='max_numb_occurrences',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
