# Generated by Django 4.1.3 on 2022-11-29 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_interval_max_numb_occurrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(16, 11, 57, 997687)),
        ),
    ]
