# Generated by Django 4.1.3 on 2022-11-29 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_interval_separation_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(16, 27, 32, 28797)),
        ),
    ]
