# Generated by Django 3.2.15 on 2022-11-30 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_interval_time_of_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='notifications.interval'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(9, 9, 49, 700900)),
        ),
    ]
