# Generated by Django 3.2.15 on 2022-12-02 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20221130_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(13, 1, 57, 753637)),
        ),
    ]
