# Generated by Django 3.2.15 on 2022-11-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='user_ref',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='user',
            new_name='user_ref',
        ),
    ]
