# Generated by Django 3.2.15 on 2022-11-24 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20221114_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='data_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='thera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.therapist'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='user_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to=settings.AUTH_USER_MODEL),
        ),
    ]
