# Generated by Django 3.2.15 on 2022-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221124_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='img_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
